name: "Run CI"

on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-lates
    steps:
      - uses: actions/checkout@v3
      - uses: pre-commit/action@v3.0.1
    
  tests:
    needs: pre-commit
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          cache: true
      - run:  pixi run test
