name: "Run CI"

on: pull_request

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          cache: true
      - run:  pixi run test

