name: "Run Doc"

on: pull_request

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          cache: true
      - run: pixi run doc
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/build/html
